#!/bin/bash

# AUTO LOGIN - Auto SSH LOGIN
#
# @category Main
# @package  AutoLogin
# @author   betta <betta0801@gmail.com>
# @license  Copyright (C) 2019 betta. All Rights Reserved

SERVER=$1
AUTO_LOGIN_CONFIG=`cat ~/.autologinrc`

if [ x"$SERVER" = x ]; then
    BORDER_LINE="\033[36m############################################################ \033[0m"
    echo -e $BORDER_LINE
    echo -e "\033[36m#                     [AUTO SSH]                           # \033[0m"
    echo -e "\033[36m#                                                          # \033[0m"

    i=0;
    if [ "$AUTO_LOGIN_CONFIG" != "" ]; then
        for server in $AUTO_LOGIN_CONFIG; do
            i=`expr $i + 1`
            SERVER=`echo $server | awk -F\| '{ print $1 }'`
            IP=`echo $server | awk -F\| '{ print $2 }'`
            NAME=`echo $server | awk -F\| '{ print $3 }'`

            LINE="\033[36m#"\ $SERVER\ -\ $IP
            MAX_LINE_LENGTH=`expr ${#BORDER_LINE}`
		    CURRENT_LINE_LENGTH=`expr "${#LINE}"`
		    DIS_LINE_LENGTH=`expr $MAX_LINE_LENGTH - $CURRENT_LINE_LENGTH - 9`

    		echo -e $LINE"\c"
            for n in $(seq $DIS_LINE_LENGTH);
		    do
		        echo -e " \c"
		    done
    		echo -e "# \033[0m"
        done
        echo -e "\033[36m#                                                          # \033[0m"
    	echo -e $BORDER_LINE
    fi
else
    echo "start login"
    SERVER_NUM=`cat ~/.autologinrc| awk -F '|' '{print NR" "$1}' | grep ${SERVER} | awk '{print $1}'`
    SERVER_INFO=`awk "NR== ${SERVER_NUM} {print}" ~/.autologinrc`

    IP=`echo $SERVER_INFO | awk -F\| '{ print $2 }'`
    NAME=`echo $SERVER_INFO | awk -F\| '{ print $3 }'`
    PASS=`echo $SERVER_INFO | awk -F\| '{ print $4 }'`
    PORT=`echo $SERVER_INFO | awk -F\| '{ print $5 }'`

    TMP_FILE="/tmp/.login.sh"
    echo '#!/usr/bin/expect -f' > $TMP_FILE
    echo 'set timeout 30' >> $TMP_FILE
    echo 'trap {' >> $TMP_FILE
    echo '    set rows [stty rows]' >> $TMP_FILE
    echo '    set cols [stty columns]' >> $TMP_FILE
    echo '    stty rows $rows columns $cols < $spawn_out(slave,name)' >> $TMP_FILE
    echo '} WINCH' >> $TMP_FILE
    echo "spawn ssh -p$PORT -l "$NAME $IP >> $TMP_FILE
    echo 'expect {' >> $TMP_FILE
    echo '    "(yes/no)?" {' >> $TMP_FILE
    echo '        send yes\r' >> $TMP_FILE
    echo '        exp_continue' >> $TMP_FILE
    echo '    }' >> $TMP_FILE
    if [ "$PASS" != "" ]; then
	    echo '    "password:" {' >> $TMP_FILE
	    echo '        send   '$PASS"\r" >> $TMP_FILE
        echo '        interact' >> $TMP_FILE
        echo '    }' >> $TMP_FILE
    fi
    echo '}' >> $TMP_FILE
    chmod a+x $TMP_FILE
    $TMP_FILE
    echo '' > $TMP_FILE
fi
